# =============================================
#   PDF Generation Module
#   Sri Lanka Banking Fraud Detection 🇱🇰
#   pdf_generator.py
# =============================================

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os
import io


class PDFGenerator:
    """Generate PDF reports for fraud detection system"""
    
    def __init__(self, output_path=None):
        self.output_path = output_path
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        
    def _setup_custom_styles(self):
        """Setup custom styles for PDF"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1D9E75'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2C3E50'),
            spaceAfter=12,
            spaceBefore=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomSubheading',
            parent=self.styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#34495E'),
            spaceAfter=8,
            spaceBefore=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#2C3E50'),
            spaceAfter=6
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomFooter',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.HexColor('#7F8C8D'),
            alignment=TA_CENTER
        ))
    
    def _add_header(self, story, title, subtitle=""):
        """Add document header"""
        story.append(Paragraph(title, self.styles['CustomTitle']))
        if subtitle:
            story.append(Paragraph(subtitle, self.styles['CustomBody']))
        story.append(Spacer(1, 0.2*inch))
    
    def _add_footer(self, story):
        """Add document footer"""
        story.append(Spacer(1, 0.5*inch))
        footer_text = f"Generated by Fraud Shield AI - Sri Lanka Banking Fraud Detection System | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        story.append(Paragraph(footer_text, self.styles['CustomFooter']))
    
    def _create_risk_table(self, risk_data):
        """Create risk assessment table"""
        data = [
            ['Risk Level', 'Probability', 'Decision', 'Timestamp'],
            [
                risk_data.get('risk', 'N/A'),
                f"{risk_data.get('prob', 0):.1%}",
                risk_data.get('decision', 'N/A'),
                datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            ]
        ]
        
        table = Table(data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1D9E75')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#ECF0F1')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, 1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, 1), 9),
        ]))
        
        return table
    
    def _create_transaction_table(self, transaction_data):
        """Create transaction details table"""
        data = [['Field', 'Value']]
        
        for key, value in transaction_data.items():
            if isinstance(value, (int, float, str, bool)):
                display_key = key.replace('_', ' ').title()
                display_value = str(value)
                data.append([display_key, display_value])
        
        table = Table(data, colWidths=[2*inch, 3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2C3E50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        
        return table
    
    def _create_alerts_table(self, alerts_data):
        """Create alerts summary table"""
        data = [['Timestamp', 'Fraud Type', 'Risk Level', 'Probability']]
        
        for alert in alerts_data:
            data.append([
                alert.get('timestamp', 'N/A'),
                alert.get('fraud_type', 'N/A'),
                alert.get('risk_level', 'N/A'),
                f"{alert.get('probability', 0):.1%}"
            ])
        
        table = Table(data, colWidths=[1.5*inch, 2*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#C0392B')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        
        return table
    
    def _create_analytics_table(self, analytics_data):
        """Create analytics summary table"""
        data = [['Metric', 'Value']]
        
        for key, value in analytics_data.items():
            display_key = key.replace('_', ' ').title()
            display_value = str(value)
            data.append([display_key, display_value])
        
        table = Table(data, colWidths=[2.5*inch, 2.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2980B9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        
        return table
    
    def generate_fraud_report(self, transaction_data, risk_data, fraud_type="Banking Fraud"):
        """Generate fraud detection report PDF"""
        story = []
        
        # Header
        self._add_header(story, 
                        "Fraud Detection Report", 
                        f"Sri Lanka Banking Fraud Detection System - {fraud_type}")
        
        # Risk Assessment Section
        story.append(Paragraph("Risk Assessment", self.styles['CustomHeading']))
        story.append(self._create_risk_table(risk_data))
        story.append(Spacer(1, 0.3*inch))
        
        # Transaction Details Section
        story.append(Paragraph("Transaction Details", self.styles['CustomHeading']))
        story.append(self._create_transaction_table(transaction_data))
        story.append(Spacer(1, 0.3*inch))
        
        # Analysis Summary
        story.append(Paragraph("Analysis Summary", self.styles['CustomHeading']))
        summary_text = f"""
        The transaction has been analyzed using advanced machine learning models. 
        Risk Level: {risk_data.get('risk', 'N/A')} 
        with a fraud probability of {risk_data.get('prob', 0):.1%}.
        Decision: {risk_data.get('decision', 'N/A')}.
        """
        story.append(Paragraph(summary_text, self.styles['CustomBody']))
        
        # Footer
        self._add_footer(story)
        
        return self._build_pdf(story)
    
    def generate_transaction_statement(self, transactions_list, account_info=None):
        """Generate transaction statement PDF"""
        story = []
        
        # Header
        self._add_header(story, 
                        "Transaction Statement", 
                        "Sri Lanka Banking Fraud Detection System")
        
        # Account Information
        if account_info:
            story.append(Paragraph("Account Information", self.styles['CustomHeading']))
            story.append(self._create_transaction_table(account_info))
            story.append(Spacer(1, 0.3*inch))
        
        # Transactions Table
        story.append(Paragraph("Transaction History", self.styles['CustomHeading']))
        
        data = [['Date', 'Amount (LKR)', 'Type', 'Risk Level', 'Status']]
        for txn in transactions_list:
            data.append([
                txn.get('date', 'N/A'),
                f"{txn.get('amount', 0):,.2f}",
                txn.get('type', 'N/A'),
                txn.get('risk', 'N/A'),
                txn.get('status', 'N/A')
            ])
        
        table = Table(data, colWidths=[1.2*inch, 1.2*inch, 1*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1D9E75')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        
        story.append(table)
        story.append(Spacer(1, 0.3*inch))
        
        # Summary
        total_amount = sum(txn.get('amount', 0) for txn in transactions_list)
        fraud_count = sum(1 for txn in transactions_list if txn.get('risk') in ['HIGH', 'CRITICAL'])
        
        story.append(Paragraph("Statement Summary", self.styles['CustomHeading']))
        summary_data = [
            ['Total Transactions', str(len(transactions_list))],
            ['Total Amount', f"LKR {total_amount:,.2f}"],
            ['High-Risk Transactions', str(fraud_count)],
            ['Statement Period', f"{datetime.now().strftime('%Y-%m-%d')}"]
        ]
        
        summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495E')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        
        story.append(summary_table)
        
        # Footer
        self._add_footer(story)
        
        return self._build_pdf(story)
    
    def generate_alerts_summary(self, alerts_data, time_period="Last 30 Days"):
        """Generate alerts summary PDF"""
        story = []
        
        # Header
        self._add_header(story, 
                        "Fraud Alerts Summary", 
                        f"Sri Lanka Banking Fraud Detection System - {time_period}")
        
        # Alerts Table
        story.append(Paragraph("Recent Alerts", self.styles['CustomHeading']))
        story.append(self._create_alerts_table(alerts_data))
        story.append(Spacer(1, 0.3*inch))
        
        # Alert Statistics
        story.append(Paragraph("Alert Statistics", self.styles['CustomHeading']))
        
        critical_count = sum(1 for a in alerts_data if a.get('risk_level') == 'CRITICAL')
        high_count = sum(1 for a in alerts_data if a.get('risk_level') == 'HIGH')
        medium_count = sum(1 for a in alerts_data if a.get('risk_level') == 'MEDIUM')
        low_count = sum(1 for a in alerts_data if a.get('risk_level') == 'LOW')
        
        stats_data = [
            ['Total Alerts', str(len(alerts_data))],
            ['Critical Risk', str(critical_count)],
            ['High Risk', str(high_count)],
            ['Medium Risk', str(medium_count)],
            ['Low Risk', str(low_count)]
        ]
        
        stats_table = Table(stats_data, colWidths=[2*inch, 2*inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#C0392B')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        
        story.append(stats_table)
        
        # Footer
        self._add_footer(story)
        
        return self._build_pdf(story)
    
    def generate_analytics_report(self, analytics_data, charts_data=None):
        """Generate analytics dashboard PDF"""
        story = []
        
        # Header
        self._add_header(story, 
                        "Analytics Dashboard Report", 
                        "Sri Lanka Banking Fraud Detection System")
        
        # Analytics Summary
        story.append(Paragraph("Performance Metrics", self.styles['CustomHeading']))
        story.append(self._create_analytics_table(analytics_data))
        story.append(Spacer(1, 0.3*inch))
        
        # Additional Analysis
        story.append(Paragraph("Analysis Overview", self.styles['CustomHeading']))
        analysis_text = """
        This report provides a comprehensive overview of the fraud detection system's performance.
        The metrics above indicate the effectiveness of the machine learning models in identifying
        fraudulent activities while minimizing false positives.
        """
        story.append(Paragraph(analysis_text, self.styles['CustomBody']))
        
        # Footer
        self._add_footer(story)
        
        return self._build_pdf(story)
    
    def _build_pdf(self, story):
        """Build PDF from story elements"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                               rightMargin=72, leftMargin=72,
                               topMargin=72, bottomMargin=18)
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def generate_comprehensive_report(self, all_data):
        """Generate comprehensive PDF report with all system data"""
        story = []
        
        # Main Header
        self._add_header(story, 
                        "Sri Lanka Banking Fraud Detection System", 
                        "Comprehensive Fraud Detection Statement")
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", self.styles['CustomHeading']))
        
        summary_data = [
            ['Report Generated', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['System Status', 'Active'],
            ['Monitoring Mode', 'Live'],
            ['Total Domains', '6'],
            ['Report Type', 'Comprehensive Statement']
        ]
        
        summary_table = Table(summary_data, colWidths=[2*inch, 2.5*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1D9E75')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Live Monitor Section
        if 'live_monitor' in all_data and all_data['live_monitor']:
            story.append(Paragraph("Live Monitor Status", self.styles['CustomHeading']))
            
            monitor_data = [['Metric', 'Value']]
            for key, value in all_data['live_monitor'].items():
                if isinstance(value, (int, float, str, bool)):
                    display_key = key.replace('_', ' ').title()
                    display_value = str(value)
                    monitor_data.append([display_key, display_value])
            
            monitor_table = Table(monitor_data, colWidths=[2*inch, 2.5*inch])
            monitor_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2980B9')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
            ]))
            
            story.append(monitor_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Pipeline Section
        if 'pipeline' in all_data and all_data['pipeline']:
            story.append(Paragraph("Pipeline Performance", self.styles['CustomHeading']))
            
            pipeline_data = [['Metric', 'Value']]
            for key, value in all_data['pipeline'].items():
                if isinstance(value, (int, float, str, bool)):
                    display_key = key.replace('_', ' ').title()
                    display_value = str(value)
                    pipeline_data.append([display_key, display_value])
            
            pipeline_table = Table(pipeline_data, colWidths=[2*inch, 2.5*inch])
            pipeline_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8E44AD')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
            ]))
            
            story.append(pipeline_table)
            story.append(Spacer(1, 0.3*inch))
        
        # Six Domains Section
        story.append(Paragraph("Six Domain Analysis", self.styles['CustomHeading']))
        
        domains = ['banking', 'ecommerce', 'mobile', 'insurance', 'loan', 'phishing']
        domain_colors = {
            'banking': '#1D9E75',
            'ecommerce': '#E67E22', 
            'mobile': '#3498DB',
            'insurance': '#9B59B6',
            'loan': '#E74C3C',
            'phishing': '#F39C12'
        }
        
        for domain in domains:
            if domain in all_data and all_data[domain]:
                story.append(Paragraph(f"{domain.title()} Domain", self.styles['CustomSubheading']))
                
                domain_data = [['Metric', 'Value']]
                for key, value in all_data[domain].items():
                    if isinstance(value, (int, float, str, bool)):
                        display_key = key.replace('_', ' ').title()
                        display_value = str(value)
                        domain_data.append([display_key, display_value])
                
                domain_table = Table(domain_data, colWidths=[2*inch, 2.5*inch])
                domain_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(domain_colors.get(domain, '#34495E'))),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 8),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                    ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
                    ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 1), (-1, -1), 7),
                ]))
                
                story.append(domain_table)
                story.append(Spacer(1, 0.15*inch))
        
        # Fraud Alerts Section
        if 'fraud_alerts' in all_data and all_data['fraud_alerts']:
            story.append(PageBreak())
            story.append(Paragraph("Recent Fraud Alerts", self.styles['CustomHeading']))
            story.append(self._create_alerts_table(all_data['fraud_alerts']))
            story.append(Spacer(1, 0.3*inch))
        
        # Analytics Summary
        if 'analytics' in all_data and all_data['analytics']:
            story.append(Paragraph("System Analytics", self.styles['CustomHeading']))
            story.append(self._create_analytics_table(all_data['analytics']))
            story.append(Spacer(1, 0.3*inch))
        
        # Footer
        self._add_footer(story)
        
        return self._build_pdf(story)